### ISSUE TITLE
Database architecture

### ISSUE THREAD

**Issue by antonve** [tadoku/api#1]
## Proposal

This is a first go at a database structure for the app. A `?` suffix of the type means that it's nullable.

### `contests`

field | type
--- | ---
id | bigint
start | date
end | date
open | boolean

primary key: `id`

### `mediums`

field | type
--- | ---
id | smallint
description | text
points | float

primary key: `id`
index: `slug`

### `users`

field | type | notes
--- | --- | ---
id | bigint
email | varchar(255)
password | bytea
role | smallint | defined by the enum in the domain
preferences | jsonb | contains stuff like the timezone of the user

primary key: `id`

### `languages`

field | type | notes
--- | --- | ---
iso_code | varchar(3) | according to ISO 639-3
name | varchar(50)

primary key: `iso_code`

### `logs`

field | type
--- | ---
id | bigint
contest_id | bigint
user_id | bigint
language_code | varchar(3)
medium_id | smallint
amount | float(3)
created_at | timestamp
updated_at | timestamp
deleted_at | timestamp?

primary key: `id`
index: `contest_id`, `user_id`, `language_code`, `medium_id`

~I'm not exactly sure if we should use `ranking_id` or a combination of `user_id` and `contest_id`. With `ranking_id` we can easily calculate the score for a certain round, but it'd be harder to agregate the overal score.~ Decided to go with `user_id` and `contest_id`.

### `rankings`

field | type | notes
--- | --- | ---
id  | bigint | 
contest_id | bigint | 
user_id | bigint  | 
language_code | varchar(3), nullable | null means all languages
score | float(3) | 
updated_at | timestamp | 

primary key: `id`
index: `contest_id`, `user_id`, `language_code`

**Comment by Hobogrammer** [comment]
Not sure how I feel about `slug` as a field name. It isn't very descriptive in this case. 

What do you think about adding `prevRank` and `currRank` to the `logs` table? I'm trying to think of an easy way to show trends in rank changes over the course of the contest.

Other than that, LGTM 😄

**Comment by antonve** [comment]
@Hobogrammer I just realized we'll need to add `language` to rankings as well, since we want to filter different scores for different languages.

**Comment by antonve** [comment]
Settled on doing so, we can always change it later as we see fit.

**Comment by antonve** [comment]
Languages and Mediums are now in-memory instead of in the database https://github.com/tadoku/api/pull/39
